#!/bin/bash 

# https://dev.to/ifenna__/adding-colors-to-bash-scripts-48g4

export black="\e[30m"
export red="\e[31m"
export green="\e[32m"
export yellow="\e[33m"
export blue="\e[34m"
export magenta="\e[35m"
export cyan="\e[36m"
export light_gray="\e[37m"
export gray="\e[37m"
export light_red="\e[91m"
export light_green="\e[92m"
export light_yellow="\e[93m"
export light_blue="\e[94m"
export light_magenta="\e[95m"
export light_cyan="\e[96m"
export white="\e[97m"

export ec="\e[0m" # ec = endcolor

#echo -e "${black}COLORED TEXT${ec} # black"
#echo -e "${red}COLORED TEXT${ec} # red"
#echo -e "${green}COLORED TEXT${ec} # green"
#echo -e "${yellow}COLORED TEXT${ec} # yellow"
#echo -e "${blue}COLORED TEXT${ec} # blue"
#echo -e "${magenta}COLORED TEXT${ec} # magenta"
#echo -e "${cyan}COLORED TEXT${ec} # cyan"
#echo -e "${light_gray}COLORED TEXT${ec} # light_gray"
#echo -e "${gray}COLORED TEXT${ec} # gray"
#echo -e "${light_red}COLORED TEXT${ec} # light_red"
#echo -e "${light_green}COLORED TEXT${ec} # light_green"
#echo -e "${light_yellow}COLORED TEXT${ec} # light_yellow"
#echo -e "${light_blue}COLORED TEXT${ec} # light_blue"
#echo -e "${light_magenta}COLORED TEXT${ec} # light_magenta"
#echo -e "${light_cyan}COLORED TEXT${ec} # light_cyan"
#echo -e "${white}COLORED TEXT${ec} # white"

