#!/bin/bash 

# This should be an the "Application Slug" that you can find on the application
# settings page. Its also embedded in the URL when you're working with an app
# in the replicated UI.
#export REPLICATED_APP='jahtomate-deer'
export REPLICATED_APP='cli-tutorial-flamingo'

replicated_ro_user_api_token='63d49e65226eee1f1650eba3fff6d331010134eafa77eb769773b3a5f8d678e3'
replicated_rw_user_api_token='d74e12165ffa4ee476a5671b74681d90aa5594a3bf3c393d747b7d8d02522bdc'

export REPLICATED_API_TOKEN=$replicated_rw_user_api_token

